name: mclaysen.com-deploy
on:
  push:
    branches: main

jobs:
  use-build: 
    uses: mclaysen/website/.github/workflows/build.yml@main
  deploy:
    name: Deploy
    needs: use-build
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: mclaysen.com-artifact
          path: build
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{secrets.SERVER_IP}}
          username: ${{secrets.SERVER_USER}}
          password: ${{secrets.SERVER_PASSWORD}}
          port: ${{secrets.SERVER_PORT}}
          local-dir: build
          server-dir: ${{env.DIRECTORY}}
