name: mclaysen.com-deploy
on:
  push: 
    branches:
      - main
      - cifix
  workflow_dispatch:
    inputs: 
      releaseType:
        description: 'Where to release (staging or production)'
        required: true
        default: 'staging'

jobs:
  staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - uses: actions/checkout@v3
      - name: Create Artifact
        uses: ./.github/actions/build
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: mclaysen.com-artifact
          path: build
      - name: Sync files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{secrets.SERVER_USER}}
          server: ${{secrets.SERVER_IP}}
          ssh_private_key: ${{secrets.SERVER_KEY}}
          local_path: './build/'
          remote_path: ${{env.DIRECTORY}}
          password: ${{secrets.SERVER_PASSWORD}}
          port: ${{secrets.SERVER_PORT}}
          sftp_only: true
  production:
    if: github.event.inputs.releaseType == 'production'
    name: Deploy to production
    runs-on: ubuntu-latest
    environment:
      name: Production
    needs: [staging]
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: mclaysen.com-artifact
          path: build
      - name: Sync files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{secrets.SERVER_USER}}
          server: ${{secrets.SERVER_IP}}
          ssh_private_key: ${{secrets.SERVER_KEY}}
          local_path: './build/'
          remote_path: ${{env.DIRECTORY}}
          password: ${{secrets.SERVER_PASSWORD}}
          port: ${{secrets.SERVER_PORT}}
          sftp_only: true
