name: mclaysen.com-deploy
on:
  push: 
    branches:
      - main
      - cifix
  workflow_dispatch:
    inputs: 
      releaseType:
        description: 'Where to release (staging or production)'
        required: true
        default: 'staging'

jobs:
  staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - uses: actions/checkout@v3
      - name: Create Artifact
        uses: ./.github/actions/build
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: mclaysen.com-artifact
          path: build
      - name: Deploy Code
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_KEY }}
          SOURCE: 'build/'
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }}
          TARGET: ${{ vars.DIRECTORY }}
  production:
    if: github.event.inputs.releaseType == 'production'
    name: Deploy to production
    runs-on: ubuntu-latest
    environment:
      name: Production
    needs: [staging]
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: mclaysen.com-artifact
          path: build
      - name: Deploy Code
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_KEY }}
          SOURCE: 'build/'
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }}
          TARGET: ${{ vars.DIRECTORY }}
